# Setup
title:               Projet IFT6758 Blog
tagline:             'A template based on the Lanyon Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://NhlHokeyVis.github.io
baseurl:             'blog'
paginate:            5
permalink:           pretty
index: blog/_posts/example.md

# About/contact
author:
  name:              Fawzi Fatima Zahra, Frank Sherif, Francis, Frida-Cecilia
  url:            
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
